### ISSUE TITLE
Incompatibility headless.storageProxy vs. EXT:filefill

### ISSUE THREAD

**Issue by kitzberger** [TYPO3-Headless/headless#418]
Activating the feature `headless.storageProxy` breaks the functionality of EXT:filefill.

I'm not really sure how to fix this, but I thought it should be documented ;-)

| Without storageProxy | With storageProxy |
| -- | -- |
| ![Bildschirmfoto vom 2022-03-17 13-56-06](https://user-images.githubusercontent.com/1405149/158815946-a4c9abd3-761a-4387-9a98-cecf467062b6.png) | ![screenshot-api doppelherz de test_8080-2022 03 17-13_57_07](https://user-images.githubusercontent.com/1405149/158815969-e5a0a312-34b7-4bfb-b999-5e4e9d5bd7e9.png) |

**Comment by twoldanski** [comment]
This solved by new package which provides custom xclass to handle it out of box.
See https://github.com/TYPO3-Headless/headless-dev-tools
