### ISSUE TITLE
html parsing not like expected

### ISSUE THREAD

**Issue by sk17philipp** [TYPO3-Headless/headless#425]
Hey, 

For the html code elements I didn't get the expected json back. For example line breaks became \r\n . Whats the reason for this behaviour. I only want to parse the html on the frontend. So I expect the html like saved on the backend.

On the pictures the html in the backend and the given json:
<img width="840" alt="Screenshot 2022-03-23 at 13 34 57" src="https://user-images.githubusercontent.com/22757133/159680359-74c66804-fa91-4acc-8388-7281441dd38f.png">

<img width="827" alt="Screenshot 2022-03-23 at 13 36 58" src="https://user-images.githubusercontent.com/22757133/159680723-eac513db-9be5-405f-b470-7d84b3e684a7.png">

**Comment by tmotyl** [comment]
Hi,
This is correct. According to JSON standard, JSON doesn't allow linebreaks like you want. See 
https://stackoverflow.com/questions/2392766/are-multi-line-strings-allowed-in-json
