### ISSUE TITLE
Reason for using "JSON_FORCE_OBJECT"?

### ISSUE THREAD

**Issue by lochmueller** [TYPO3-Headless/headless#450]
Hey everyone,

we create real arrays in some datastructures and found out, that the empty arrays are objects.
We found this in the code: https://github.com/TYPO3-Headless/headless/blob/master/Classes/ContentObject/JsonContentContentObject.php#L101

Why is this options used? Is there any reason for it or could we disable this option.

I think if there is a real array data structure, it is cooler to send an empty array instead an empty object, isn't it?

Regards,
Tim

**Comment by twoldanski** [comment]
content is object, so therefore empty content node should be also empty object and not array (we should not change type)
