### ISSUE TITLE
FR: Support for EXT:workspaces

### ISSUE THREAD

**Issue by kitzberger** [TYPO3-Headless/headless#460]
Would be cool to have full support of TYPO3's workspaces functionality incl. preview and slider comparision in the FE.

What would be the necessary changes? Thinking about creating a PR for that since one of our customers is in need for that feature.

**Comment by twoldanski** [comment]
Yes, that is my 'next big thing' on my list also, but main job will be on the frontend side

**Comment by lukaszuznanski** [comment]
Well, not really, as its only iframe so frontend base could be used. When I checked it, it should be very easy to implement.
