### ISSUE TITLE
TypoLink parsing of link wizard format using 'returnLast = result' not working

### ISSUE THREAD

**Issue by jochenrieger** [TYPO3-Headless/headless#462]
When defining a TCA field with a link wizard and setting things like target (eg. "_blank"), CSS class or title attribute, the API result fields for those attributes show `null` as value and the `href` field contains the full typolink format, for example:

`https://www.google.de _blank header-link-css-class &quot;Header link title attribute text&quot;`

It seems the string is not correctly parsed and hence the target / title / class / additionalAtrributes etc. stay empty / `null` in the API result.

The general transition from a pure `string` field to an object works fine when using `returnLast = result` in the TypoScript config for the field works as expected.

Example field config:

```
linkTarget = TEXT
linkTarget {
  field = tx_mask_teaser_link
  htmlSpecialChars = 1

  typolink.parameter.field = tx_mask_teaser_link
  typolink.returnLast = result
}
```

Screenshot Link Wizard:

![Screenshot 2022-07-13 at 15 50 47](https://user-images.githubusercontent.com/8180661/178815854-183a5179-eecd-40cd-98cc-5c6f62b4fc7b.png)

Screenshot API response for field:

![Screenshot 2022-07-13 at 15 50 36](https://user-images.githubusercontent.com/8180661/178815921-9319a4d6-29d4-4b9a-ba10-b0a686c9a6cf.png)

---

Tested with `EXT:headless` `3.0.4` and TYPO3 `11.5.[11|12|13]`

**Comment by lukaszuznanski** [comment]
Please wait for 11.5.15 release and double check it with new headless v3.1.0

**Comment by jochenrieger** [comment]
@lukaszuznanski 

Thanks for the update. I'll gladly check it with the next T3 release 11.5.14 and the latest 3.1.0 version of `EXT:headless`.

In terms of the T3 core update, is there any issue / fix in particular that I could have an eye on (and maybe test it before the official release)?

**Comment by twoldanski** [comment]
@jochenrieger to clarify issue is with the core TYPO3, not headless, so you can test on any version 3 of headless (right now if you updated TYPO3 to >11.5.11 you have broken links. Core devs are fixing it, see more at https://review.typo3.org/c/Packages/TYPO3.CMS/+/75366

**Comment by jochenrieger** [comment]
Awesome! Thanks for the link to the issue @twoldanski

**Comment by jochenrieger** [comment]
Just to give an update here:

Tested it successfully with 

`"typo3/cms-core": "^11.5@dev"`

and `EXT:headless` v3.1.2

==> Worked like a charm with both `returnLast = url` and `returnLast = result`

**Comment by twoldanski** [comment]
With release of TYPO3 11.5.15 issue is resolved with any version of EXT:headless v3.x
