### ISSUE TITLE
Missing fileExtension propertie in FileUtility.php

### ISSUE THREAD

**Issue by kubilaymelnikov** [TYPO3-Headless/headless#475]
I would like to add this line to the `FileUtility` so that you can also create `webp` directly with the processor.

## TYPO3 Headless
It is about this method
[FileUtility:: processImageFile](https://github.com/TYPO3-Headless/headless/blob/4569d2a536b920105e9796b072ab0f7ddab4fe2d/Classes/Utility/FileUtility.php#L149-L181)

## TYPO3
From here I have the cutout
[ImageViewHelper:: renderStatic](https://github.com/TYPO3/typo3/blob/16475a7cf41214eefdf89b0c047571f23f217ba6/typo3/sysext/fluid/Classes/ViewHelpers/Uri/ImageViewHelper.php#L150-L152)

## Changed Files
```php
// FriendsOfTYPO3\Headless\Utility\FileUtility::processImageFile
$processingInstructions = [
    'width' => $dimensions['width'] ?? null,
    'height' => $dimensions['height'] ?? null,
    'minWidth' => $dimensions['minWidth'] ?? $properties['minWidth'] ?? 0,
    'minHeight' => $dimensions['minHeight'] ?? $properties['minHeight'] ?? 0,
    'maxWidth' => $dimensions['maxWidth'] ?? $properties['maxWidth'] ?? 0,
    'maxHeight' => $dimensions['maxHeight'] ?? $properties['maxHeight'] ?? 0,
    'crop' => $cropArea->isEmpty() ? null : $cropArea->makeAbsoluteBasedOnFile($image),
];
// NEW LINES START
if (!empty($dimensions['fileExtension'] ?? '')) {
    $processingInstructions['fileExtension'] = $dimensions['fileExtension'];
}
// NEW LINES END
return $this->imageService->applyProcessingInstructions($image, $processingInstructions);
```

```php
// FriendsOfTYPO3\Headless\DataProcessing\FilesProcessor::process
$properties = [];

if (isset($processorConfiguration['processingConfiguration.'])) {
    $properties = $processorConfiguration['processingConfiguration.'];
}

$this->contentObjectRenderer = $cObj;
$this->processorConfiguration = $processorConfiguration;

$targetFieldName = (string)$cObj->stdWrapValue(
    'as',
    $this->processorConfiguration,
    $this->defaults['as']
);

$this->fileObjects = $this->fetchData();
$processedData[$targetFieldName] = $this->processFiles($properties);
```

## Example typoscript definition
```typoscript
images = TEXT
images {
  dataProcessing {
    10 = FriendsOfTYPO3\Headless\DataProcessing\FilesProcessor
    10 {
      processingConfiguration {
        fileExtension = webp
      }
      references.fieldName = images
      as = media
    }
  }
}
```

**Comment by jochenrieger** [comment]
Sounds great and a good thing to have in the API response by default.

We also patched the file utility in our current project to also add the file meta data fields to add some of the fields that come with the activation of the TYPO3 core extension `typo3/cms-filemetadata`, specifically the fields that contain information related to `copyright`, `creator`, `publisher`, `source` which might be a common use case for those using images from stocks / photographers that need to be named in the caption. 

It's just a quick patch adding these fields to the response. It might make sense to add some kind of condition / dependency checking for an active `typo3/cms-filemetadata`.

**Comment by lukaszuznanski** [comment]
Hi,

it's actually not a way to generate .webp image. You don't process image to .webp by changing file extension. Please take a look at https://github.com/plan2net/webp extension, it works perfectly fine with headless, but it has to be done on server side, not in headless at all. 
Next time, please create pull request with your changes. 

When it comes to cms-filemetadata @jochenrieger, please create another issue. Closing this one as it's not relevant at all. Please reopen if you have any further questions.

**Comment by kubilaymelnikov** [comment]
That's not quite true, if you add webp as file format in the configuration you can create webp images normally with the image processing within TYPO3.
`$GLOBALS['TYPO3_CONF_VARS']['GFX']['imagefile_ext'] = 'gif,jpg,jpeg,tif,tiff,bmp,pcx,tga,png,pdf,ai,svg,webp';`

However, this issue is not primarily about webp but about taking away the possibility to define a filetype.

**Comment by lukaszuznanski** [comment]
@kubilaymelnikov ok, I was not aware that TYPO3 was able to process webp right now. I will dig into this then.

Please provide pull request with your changes.

**Comment by kubilaymelnikov** [comment]
@lukaszuznanski yes, as soon as i have time to install it cleanly!

**Comment by kubilaymelnikov** [comment]
@lukaszuznanski & @twoldanski
I test this today and then start the pull request.
