### ISSUE TITLE
JsonView backend module error

### ISSUE THREAD

**Issue by do-web** [TYPO3-Headless/headless#488]
If try to open the JsonView Backend Module i got an error:

`
FriendsOfTYPO3\Headless\Utility\FileUtility::getNormalizedParams(): Return value must be of type TYPO3\CMS\Core\Http\NormalizedParams, null returned

in /var/www/html/public/typo3conf/ext/headless/Classes/Utility/FileUtility.php line 251

    protected function getNormalizedParams(): NormalizedParams
    {
        return $this->serverRequest->getAttribute('normalizedParams');
    }
`

It seams that $this->serverRequest->getAttribute('normalizedParams') is null.

**Comment by twoldanski** [comment]
Hi @do-web, could you provide more context? TYPO3 version, headless version, and some steps to reproduce it?

**Comment by twoldanski** [comment]
I'm closing issue as this functionality was moved to https://github.com/TYPO3-Headless/headless_dev_tools package
cc @lukaszuznanski
