### ISSUE TITLE
Missing image metadata

### ISSUE THREAD

**Issue by t3touch** [TYPO3-Headless/headless#499]
I don't know what my mistake is. But in my TYPO3 11 the image metadata are empty. This bug was reported 2019 and was fixed. Do I miss some configuration?

```
 "properties": {
    "title": null,
    "alternative": null,
    "description": null,
    "link": null,
    "linkData": null,
    "mimeType": "image/png",
    "type": "image",
    "filename": "csm_anAvatar_891bacbda0.png",
    "originalUrl": "/fileadmin/user_upload/anAvatar.png",
    "uidLocal": null,
    "fileReferenceUid": 2,
```

<img width="919" alt="grafik" src="https://user-images.githubusercontent.com/1329120/197454060-41eeffbe-54e5-415d-acb3-31182a4b3a9f.png">

**Comment by t3touch** [comment]
I just figured out, that the metadata from the sys_file is used. But I wanna use the link of the sys_file_reference.

**Comment by twoldanski** [comment]
Hi @t3touch what element did you use? Or did you use Gallery processor for it ?

**Comment by t3touch** [comment]
Hi @twoldanski I have nothing changed. Think the gallery processor is used

**Comment by twoldanski** [comment]
Hi @t3touch, could check if issue persist with version 3.2 of headless?

**Comment by t3touch** [comment]
Oh no, I had used the 3.1. Don't know why. But with the 3.2 it works perfectly. Thanks for the hint
