### ISSUE TITLE
No cookie from felogin

### ISSUE THREAD

**Issue by t3touch** [TYPO3-Headless/headless#509]
I have problems with the felogin implementation. The response message shows the login successful message. But the fe_login_user cookies is missing. FE cookie domain was set in LocalConfiguration. I use TYPO3 11.

**Comment by t3touch** [comment]
Sorry, this problem is not headless related. I have some cors issues in my axios post.

**Comment by lukaszuznanski** [comment]
You need to set proper cookie domain for your frontend cookie. This is TYPO3 configuration. For example, I use api.example.com as domain for TYPO3, and example.com for frontend nuxt-TYPO3, so I can set frontend cookie domain to *.example.com, and then your cookie will appear.

**Comment by t3touch** [comment]
BIG THANKS for your quick response. 
:raised_hands: IT WORKS.

**Comment by nabossha** [comment]
@t3touch @lukaszuznanski  i encounter the exact same problem as you do, but even with the cookieDomain correctly set in the backend:

- frontend: https://localhost:3000 
- API: https://somesite.ddev.site
- TYPO3_CONF_VARS->FE->cookieDomain: 'localhost'

i use EXT:headless (https://github.com/TYPO3-Headless/headless/commit/c12a00003a485d065f47643aa0c9095ede44a225) with TYPO3 11.5.18 and nuxt-typo3 1.0.0

the cookie for fe_typo_user seems to be returned correctly - but it looks i am still missing something as i can not locate it in the browsers cookie-storage:
![cookie-fe-user](https://user-images.githubusercontent.com/3851681/200938121-8964d872-489d-4432-9e77-adff9eb559f8.png)

any input would be greatly appreciated, thanks!

**Comment by t3touch** [comment]
The FE domain should be the same as your BE. On localhost my login also failed. 

And .ddev.site or *.ddev.site as the value in T3 settings should work.

**Comment by lukaszuznanski** [comment]
Yes, you need to use domain. Please set domain. If you need any further help, please reopen.
