### ISSUE TITLE
b13/container usage

### ISSUE THREAD

**Issue by t3touch** [TYPO3-Headless/headless#519]
This is no issue, just a short question. 
Is currently https://packagist.org/packages/fanor51/headless-container-support the only way to use container with headless?

**Comment by lukaszuznanski** [comment]
I think there is also implementation of grid_elements, but preferable way is to use b13/container with headless support

**Comment by t3touch** [comment]
Ok, thanks. I just figured out theres no need the Fanor EXT. 
With this TS I got also the content of my container elements by using the B13 Dataprocessor instead of Fanor's.  :see_no_evil:

```
tt_content.b13-1col {
    fields {
        content = TEXT
        content {
            dataProcessing {
                10 = B13\Container\DataProcessing\ContainerProcessor
                10 {
                    colPos = 200
                    as = left
                }
            }
        } ...
```
