### ISSUE TITLE
Fix storagePid in frontend login form

### ISSUE THREAD

**Issue by mm-mhelber** [TYPO3-Headless/headless#534]
Hey,

in headless v3.2.2 the **\FriendsOfTYPO3\Headless\XClass\Controller\LoginController** needs a minor fix.
TYPO3 11.5.20 introduced a feature _security.frontend.enforceLoginSigning_ which effects the evaluation of the storage pid when the user record is fetched from the database.

Therefore the LoginController line 66 needs to be adjusted accordingly to the corresponding line from the TYPO3 Core

old:
`'storagePid' => implode(',', $this->getStorageFolders()),`

new: 
`'storagePid' => $this->shallEnforceLoginSigning() ? $this->getSignedStorageFolders() : implode(',', $this->getStorageFolders()),`

Thanks for fixing!

**Comment by lukaszuznanski** [comment]
Hi, 

thanks for the information! Maybe you could provide PR with those changes, so you got a contribution to the project (as you already found out how to fit it). 

Thanks!

**Comment by twoldanski** [comment]
resolved by #535
