### ISSUE TITLE
Move hardcoded labels to xlf files for translation

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Headless/headless#545]
In order to be able to translate extension labels in Crowdin,the language xlf file needs to be created and hardcoded labels needs to be moved there (e.g. for site configuration).

**Comment by canpse** [comment]
Hello, I don't know Crowdin but if you help me find the hardcoded labels I am sure I can help you make the xlf file.

**Comment by tmotyl** [comment]
thanks @canpse.
you can see some here: https://github.com/TYPO3-Headless/headless/blob/master/Configuration/SiteConfiguration/Overrides/site.php
and 
https://github.com/TYPO3-Headless/headless/blob/master/Configuration/SiteConfiguration/Overrides/site_base_variant.php
