### ISSUE TITLE
Allow custom properties for files

### ISSUE THREAD

**Issue by dvdmlln** [TYPO3-Headless/headless#557]
Hi,

currently it is not possible to use custom properties added to `sys_file_reference`.
`FileUtility` has a fixed set of properties and does not take custom `sys_file_reference` columns into account, however they are available in `$metaData`.
My proposal is to add an event to modify properties in `FileUtility`:

```php
public function processFile(...): array
{
        $processedProperties = [
           // default properties
        ];
        
        // event to add custom properties
        $event = $this->eventDispatcher->dispatch(new ModifyFilePropertiesEvent($processedProperties, $metaData));
        $processedProperties = $event->getProperties();
        
        return [
            'publicUrl' => $publicUrl,
            'properties' => array_merge($originalProperties, $processedProperties),
        ];
}
```

I'd be happy to create a PR if this feature is something to be considered.

Best regards
David

**Comment by twoldanski** [comment]
@dvdmlln we have already PR for that https://github.com/TYPO3-Headless/headless/pull/541/files

**Comment by twoldanski** [comment]
@dvdmlln I think we can use this to achieve the same result https://github.com/TYPO3-Headless/headless/pull/541/files

**Comment by tmotyl** [comment]
@dvdmlln how is this solved in the core? do you have to use custom event to get custom file data?

**Comment by dvdmlln** [comment]
> @dvdmlln I think we can use this to achieve the same result https://github.com/TYPO3-Headless/headless/pull/541/files

Sorry, I didn't see this one.
With [this PR](https://github.com/TYPO3-Headless/headless/pull/555) `$metaData` will be removed anyway, so my proposal wouldn't work.
Regarding the PR you mentioned: at the point the event is dispatched, `$fileReference` may has been modified by `$this->processImageFile`, so the custom properties are lost. Passing something like `$originalFileReference` to the event as well should be sufficient though.


> @dvdmlln how is this solved in the core? do you have to use custom event to get custom file data?

You can just access the FileReference containing all custom properties in the frontend I guess so there isn't any extra step.
