### ISSUE TITLE
EXT:headless requires EXT:form even if it is not marked as required

### ISSUE THREAD

**Issue by bmack** [TYPO3-Headless/headless#608]
Hey team,

I wanted to use EXT:headless, but I got this error in TYPO3 v12.4.2.

The main issue is that EXT:headless apparantly needs EXT:form, even if it is not mentioned in the composer.json file.

It can also be managed to wire the service manually depending on EXT:form being present or not.
<img width="1157" alt="Screenshot 2023-06-17 at 01 31 05" src="https://github.com/TYPO3-Headless/headless/assets/165630/7bc262fd-495c-4293-9266-ae6122e84a44">

**Comment by twoldanski** [comment]
@bmack Thank you for reporting! Patch prepared :)
