### ISSUE TITLE
GalleryProcessor vs. FilesProcessor options

### ISSUE THREAD

**Issue by kitzberger** [TYPO3-Headless/headless#617]
The options of `GalleryProcessor` and `FilesProcessor` aren't really documented at the moment. I'd like to change that, but I'm afraid I need some input first ;-)

See PR #618 for an image documentation.

### Question 1: what's the `FilesProcessor` option `delayProcessing` for?

Is it used to skip image processing in `FilesProcessor` and let the 2nd data processor `GalleryProcessor` do that?

:heavy_check_mark: Yes.

### Question 2: is `GalleryProcessor` not supporting `fileExtension` yet?

Since #498 it's possible to specify a custom image format (e.g. `webp`) and the rendered image is being converted to that format.

:seedling: See PR #619 for the solution.

### Question 3: should we make the `autogenerate` option configurable?

Currently the option `autogenerate` has two hardcoded sub-options: `retina2x` and `lqip`. If activated additional image URIs are being rendered for which constants from `FileUtility` are used to calculate the width and height of that 'variants'.

In both `FilesProcessor` and `GalleryProcessor` it's basically the same code to do that. The only difference is that `GalleryProcessor` doesn't pass along other options like `fileExtension`.

Maybe those parts could be refactored to be entirely configurable via TypoScript? 

:seedling: See PR #620 for the solution.

**Comment by twoldanski** [comment]
Hi, 
Q1: Yes, this is performance flag to inform FilesProcessor only to collect files and then pass them to GalleryProcessor in order to avoid double processing of the same files (first in FileProcessor and then again in GalleryProcessor) 
Q2: No, currently not supporting it. 
Q3: Of course we could, but you have some use case for it?
