### ISSUE TITLE
LoginController -> Too few arguments to function TYPO3\CMS\FrontendLogin\Event\BeforeRedirectEvent::__construct() < v4.1

### ISSUE THREAD

**Issue by tobiasquadflieg** [TYPO3-Headless/headless#621]
BeforeRedirectEvent needs as third parameter the request, causing too few arguments exception.
This seems to be fixed in >v4.1 but in all versions below the error is present.

https://github.com/TYPO3-Headless/headless/blob/5d142ffcc5ff7d2955d5c82fffd89ee513303616/Classes/XClass/Controller/LoginController.php#L99

**Comment by twoldanski** [comment]
Oh, this changes everything. I checked on v11 and it broken. TYPO3 changed signature of event class... in maintenance release. I prepared a patch to address it on 3.x branch.

**Comment by twoldanski** [comment]
Merged with 3.x branch
