### ISSUE TITLE
FileProcessor: Exception in FileUtility while getting property width on a non-image file

### ISSUE THREAD

**Issue by christophlehmann** [TYPO3-Headless/headless#640]
**Describe the bug**

Exception: Property "width" was not found in file reference or original file.

It occurs in https://github.com/TYPO3-Headless/headless/blob/master/Classes/Utility/FileUtility.php#L116 on a non-image file

**To Reproduce**
1. Use the file processor
2. Use a non-image file in the FAL-field

**Expected behavior**

* I don't get an Exception
* Image properties are not visible

**Screenshots**

**TYPO3 version and TYPO3 Headless version**

TYPO3 v11
Headless ^3.4

**Comment by twoldanski** [comment]
Hi @christophlehmann, thank you for report. Could elaborate how you are using FileProcessor, so you get the exception? And what type of file are you using when throwing exception ? And what exception exactly ?

**Comment by twoldanski** [comment]
@christophlehmann thank you, I'm checking with default uploads element and I did not have any error when attaching zip or html file, on TYPO3 11 or TYPO 12, do you have some custom setup with TYPO3 or standard version?

**Comment by christophlehmann** [comment]
@twoldanski Also with the default uploads element i get the Exception, when i attach an html file. I have not custom setup

Here is the TypoScript of the uploads element
<img width="919" alt="Bildschirmfoto 2023-09-07 um 13 12 51" src="https://github.com/TYPO3-Headless/headless/assets/4953689/52472caa-cfc8-43ed-b3b3-9f4141a0992a">

Why should we use `getProperty('width')` on a non-image/video file reference? At least we should check if the property is there with `hasProperty()`.

**Comment by christophlehmann** [comment]
Okay, seems to be an issue with historical files in the database. They don't have metadata records, where freshly uploaded files have. Meanwhile we are on v12 and the problem is solved with the scheduler task for metadata extraction.
