### ISSUE TITLE
Custom validation errors ignored in EXT:form JSON output

### ISSUE THREAD

**Issue by Browserwerft** [TYPO3-Headless/headless#690]
**Describe the bug**
Custom error messages set via the EXT:form editor interface are missing from the JSON output. Only the default TYPO3 error message is output, but not the custom one.
![Bildschirmfoto 2024-01-02 um 14 38 42](https://github.com/TYPO3-Headless/headless/assets/58388475/8f883ab9-2f50-486a-ba28-723393da1162)

**To Reproduce**
1. Create a form with any field type
2. Add any validator to the field
3. Set a custom error message for the validator
4. See "validationErrorMessages" for this field in the JSON output 

**Expected behavior**
Custom error messages should override the default messages in the JSON output.

**TYPO3 version and TYPO3 Headless version**
TYPO3 v11
TYPO3 Headless v3.4.1

**Comment by twoldanski** [comment]
hi @Browserwerft in release `v4.3` / `v3.4.2` I added additional `customMessage` to output message directly from TYPO3 backend, so you can use message from panel or automatic translation.
