### ISSUE TITLE
Contribution of EXT:headless_mask & EXT:headless_blog

### ISSUE THREAD

**Issue by nitsan-technologies** [TYPO3-Headless/headless#706]
Hey there,

We patiently waited in the TYPO3 Slack channel to address this matter. Nonetheless, let's summarize it here.

We've created two significant extensions outlined below.
- https://github.com/nitsan-technologies/ns_headless_blog
- https://github.com/nitsan-technologies/ns_headless_mask

We wish to contribute them to the `TYPO3 Headless Community` at https://github.com/TYPO3-Headless. What is the process?

Looking forward to your reply. Thank you!

Best regards, NITSAN Team

**Comment by lukaszuznanski** [comment]
@nitsan-technologies I told you to reach me directly on slack. Let's continue this discussion on slack.

**Comment by nitsan-technologies** [comment]
Hey @lukaszuznanski 

Thank you for your assistance in releasing these two extensions to the `TYPO3 Headless` family.

One outstanding matter remains: Enabling composer support by publishing them at https://packagist.org/packages/friendsoftypo3/. 

Despite reaching out to various individuals as per your advice, we haven't been able to accomplish this task. Your assistance would be greatly appreciated.

Cheers, Team NITSAN
