### ISSUE TITLE
Images get reprocessed on every request

### ISSUE THREAD

**Issue by develth** [TYPO3-Headless/headless#768]
**Describe the bug**
Images that get processed by GalleryProccesor get processed on every request, because hash is different caused by missing fileExtension

**To Reproduce**
1. Create Gallery
2. Put Images in it
3. See how Images get processed every time via xdebug or the processed image table

**Expected behavior**
Images should be reused, cache should be equal before & after process

**TYPO3 version and TYPO3 Headless version**
latest TYPO3 & Headless

**Additional context**
Issue caused by removal of FileExtension before processing (see [here](https://github.com/TYPO3-Headless/headless/pull/724/files/a41b4fa59513d52fa0d36425d649cd1b125dbf90#diff-73a43ca8efd78b80f932a65fdec2e8e053949dda77a016c73ea5df493da8bad4L194) )

The FileExtension is not included in Options anymore, but the Repository saves the processed file **including** the fileExtension, so Hash is always different.
Hash Check in [ProcessedFileRepository](https://github.com/TYPO3/typo3/blob/12.4/typo3/sysext/core/Classes/Resource/ProcessedFileRepository.php#L235) - debugger could set here to compare hashes on search & on persist

**Comment by twoldanski** [comment]
@develth thx for issue. Can reproduce issue on `dev-master` ?

**Comment by twoldanski** [comment]
Hi @develth did you have a chance to verify if issue is reproducible on your end  on `dev-master` branch ?

**Comment by develth** [comment]
@twoldanski sorry, no time until now.
just checked out 4.4.0 & it seems to be fixed. thanks!
