### ISSUE TITLE
Wrap loading if seo in condition or adde typo3/cms-seo as requirement in composer.json

### ISSUE THREAD

**Issue by thomashohn** [TYPO3-Headless/headless#780]
**Describe the bug**
It would be nice to have the loading of the seo functionality wrapped in an if clause in the
ext_local.conf to avoid errors if typo3/cms-seo is not loaded. Everything else wrapped nice.

Alternatively add typo3/cms-seo as requirement in composer.json

**To Reproduce**
1. Install friendsoftypo3/headless >= 4.4.0
2. Frontend/Backend can crash

**Expected behavior**
The site should no crash with errors.

**TYPO3 version and TYPO3 Headless version**
TYPO3 12.4.20 and friendsoftypo3/headless >= 4.4.0

**Comment by twoldanski** [comment]
Resolved with #781
