### ISSUE TITLE
Declaration of LoginFormViewHelper incompatible with TYPO3 12.4.21

### ISSUE THREAD

**Issue by saneinsane** [TYPO3-Headless/headless#788]
In the latest update the declaration was changed from
```protected function renderHiddenIdentityField(?mixed $object, ?string $name): string```
to
```protected function renderHiddenIdentityField(?object $object, ?string $name): string```
This leads to Declaration mismatch errors.

https://github.com/TYPO3-Headless/headless/blob/e87413bb69861c2fd089cbf92171aa513b9858c7/Classes/ViewHelpers/LoginFormViewHelper.php#L213

**Comment by twoldanski** [comment]
Fixed with release https://github.com/TYPO3-Headless/headless/releases/tag/v4.4.1
