### ISSUE TITLE
Declaration  TYPO3\CMS\Fluid\ViewHelpers\Form\AbstractFormViewHelper::renderHiddenIdentityField changed in 13 LTS

### ISSUE THREAD

**Issue by cehret** [TYPO3-Headless/headless#789]
**Describe the bug**
Fatal error: Declaration of FriendsOfTYPO3\Headless\ViewHelpers\LoginFormViewHelper::renderHiddenIdentityField(?object $object, ?string $name): string must be compatible with TYPO3\CMS\Fluid\ViewHelpers\Form\AbstractFormViewHelper::renderHiddenIdentityField(mixed $object, ?string $name): string in vendor\friendsoftypo3\headless\Classes\ViewHelpers\LoginFormViewHelper.php on line 214

**To Reproduce**
Update to 13 LTS

**Expected behavior**
no error

**TYPO3 version and TYPO3 Headless version**
TYPO3 13.4.0 LTS headless dev-t3v13

**Solution**
in vendor/friendsoftypo3/headless/Classes/ViewHelpers/LoginFormViewHelper.php line 214:

change
 protected function renderHiddenIdentityField(?object $object, ?string $name): string
to
 protected function renderHiddenIdentityField(**mixed** $object, ?string $name): string

because it was changed in vendor/typo3/cms-fluid/Classes/ViewHelpers/Form/AbstractFormViewHelper.php

**Comment by twoldanski** [comment]
Resolved on rebased branch `t3v13`
