### ISSUE TITLE
Order of dataProcessing, process dataProcessing on top level same as below

### ISSUE THREAD

**Issue by lukaszuznanski** [TYPO3-Headless/headless#90]
Changing the dataprocessing on the toplevel JSON (not on the fields) to something like this
- dataprocessing changes cObj->data
- fields statements then can pick their content
Needs some more thinking for:
- nested structures like resolved flexforms, how to pick whole chunks or deep nested fields

**Comment by tmotyl** [comment]
@lukaszuznanski please update the issue - is it still valid?
